### ISSUE TITLE
"ImportError: cannot import name 'observe'"

### ISSUE THREAD

**Issue by liavkoren** [hahnlee/ipytracer#14]
Hi, using python 3.6.1, venv, Jupyter v 5.0.0, I just tried the bubblesort demo in a fresh venv and got "ImportError: cannot import name 'observe'". [Stack trace + `$ pip freee`](https://gist.github.com/liavkoren/2cf82031b3779f09dba70523974433f1).

**Comment by sn0wle0pard** [comment]
Hi, First of all thank you for leaving the issue. In my case, there was no problem in the same environment. I'll try a little more, but it seems to be a problem with traitlets. Can you try development installation and tell me the results?
```
$ git clone https://github.com/sn0wle0pard/ipytracer.git
$ cd ipytracer
$ pip install -e .
$ jupyter nbextension install --py --symlink --sys-prefix ipytracer
$ jupyter nbextension enable --py --sys-prefix ipytracer
```

**Comment by liavkoren** [comment]
Hi @sn0wle0pard. I don't think this is your problem. I think it's related to the Jupyter weirdness I've mentioned in the Jupyter Client issue.

**Comment by liavkoren** [comment]
Hey, I'm not sure if my system is particularly messed up right now, or jupyter notebook is kind of unstable ATM, but you might be amused to know that I had to work through [two](https://github.com/jupyter-widgets/ipywidgets/issues/541) [addition](https://github.com/jupyter-widgets/ipywidgets/issues/1454) pretty confusing bugs before I finally got the bubblesort demo working in a fresh venv. : D
